"""empty message

Revision ID: 52f208bf2e45
Revises: 
Create Date: 2018-05-31 12:12:57.073072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f208bf2e45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('senha', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('dt_nascimento', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('pessoa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('pessoas')
    # ### end Alembic commands ###
