"""empty message

Revision ID: 796db719a85b
Revises: 9d4460b15b99
Create Date: 2019-01-11 10:15:36.794475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796db719a85b'
down_revision = '9d4460b15b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execucoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=20), nullable=True),
    sa.Column('algoritmo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['algoritmo'], ['algoritmos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagens_da_execucao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagem', sa.String(length=500), nullable=True),
    sa.Column('execucao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['execucao'], ['execucoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faces_da_imagem_da_execucao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('face', sa.String(length=500), nullable=True),
    sa.Column('id_reconhecimento', sa.String(length=10), nullable=True),
    sa.Column('confianca_reconhecimento', sa.String(length=10), nullable=True),
    sa.Column('imagem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['imagem'], ['imagens_da_execucao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faces_da_imagem_da_execucao')
    op.drop_table('imagens_da_execucao')
    op.drop_table('execucoes')
    # ### end Alembic commands ###
