"""empty message

Revision ID: 9d4460b15b99
Revises: 
Create Date: 2018-05-31 17:10:51.840005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4460b15b99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### Notas auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('senha', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('dt_nascimento', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('pessoa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pasta_dos_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=True),
    sa.Column('algoritmo', sa.Text(), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic Notas ###


def downgrade():
    # ### Notas auto generated by Alembic - please adjust! ###
    op.drop_table('pasta_dos_usuarios')
    op.drop_table('usuarios')
    op.drop_table('pessoas')
    # ### end Alembic Notas ###
